#!/bin/bash

# #SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=TrainViTMask
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --time=24:00:00
#SBATCH --mem=100000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/Patch-DiffMask/code
source activate dl2
srun python -u main_mnist1.py
